### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by brogalan-blora** [RatJuggler/guinea-bot#13]
![Screenshot_20210205-184959](https://user-images.githubusercontent.com/78091059/107030366-202d2a00-67e3-11eb-962c-5763cbbdcf21.png)
after I enter the token and it's always an error After I entered the order Guinea --test'. 
i am using ubuntu vps 
🙏

**Comment by RatJuggler** [comment]
Hello! It looks like it cannot find the API tokens. I did not explain very well how to set the environment variables.  Could you please try setting the tokens by entering them on the command line. So enter these commands, replacing the ... with each key:

export TWITTER_CONSUMER_KEY="..."
export TWITTER_CONSUMER_SECRET="..."
export TWITTER_ACCESS_TOKEN="..."
export TWITTER_ACCESS_TOKEN_SECRET="..."

Then try:

guineabot --test

I will look at updating the documentation to better explain.

**Comment by RatJuggler** [comment]
Hello again, I've made some changes to make setting the environment variables easier and updated the README.

Try pulling the changes (git pull) and reinstalling (just use "pip3 install -U ." again).

**Comment by brogalan-blora** [comment]
![Screenshot_20210207-135858](https://user-images.githubusercontent.com/78091059/107139452-d3b22d80-694d-11eb-978a-db763ee8db49.png)
![Screenshot_20210207-140650](https://user-images.githubusercontent.com/78091059/107139455-db71d200-694d-11eb-8c41-873d8bef3e73.png)
after entering the command GuineaBot --test is verified.
And I still can't activate the service ..? 
I do not know where my mistake is ...

**Comment by RatJuggler** [comment]
Hi, did you set a user in the guinea-bot.service file?

I left the user set as `User=pi` because I run it on my own Raspberry Pi set-up at home. I have not tried running it on a cloud service.

You could try using `User=root`.

**Comment by RatJuggler** [comment]
Closing as no further response.
